/*
 * Copyright 2026 Ghaylan Saada
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.ghaylan.validata.samples.matrix

import io.ghaylan.validata.samples.constraint.OddYears
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.Arguments
import org.junit.jupiter.params.provider.MethodSource
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc
import org.springframework.http.MediaType
import org.springframework.test.web.servlet.MockMvc
import org.springframework.test.web.servlet.post
import tools.jackson.databind.ObjectMapper
import java.util.stream.Stream

/**
 * Acceptance coverage: every built-in constraint annotation plus the sample custom [OddYears],
 * generated by KSP and executed through MockMvc.
 *
 * Payloads come from [AllConstraintsFixtures]. Engine semantics for individual constraints live
 * in `validata-core`; [AllConstraintsEngineTest] only smokes the non-web `validate(params)` path.*
 * 
 * @author Ghaylan Saada
 */
@SpringBootTest
@AutoConfigureMockMvc
class AllConstraintsIT(
	/** MockMvc against the sample Boot application.	 */
	@Autowired
	val mockMvc: MockMvc,
	/** Application JSON mapper — same serialization as runtime requests.	 */
	@Autowired
	val objectMapper: ObjectMapper,
) {
	
	@Test
	@DisplayName("accepts a payload that satisfies every built-in constraint and OddYears")
			/** accepts a payload that satisfies every built-in constraint and OddYears			 */
	fun acceptsFullyValidPayload() {
		mockMvc.post("/api/all-constraints") {
			contentType = MediaType.APPLICATION_JSON
			content = json(AllConstraintsFixtures.valid())
		}
			.andExpect {
				status { isOk() }
				content { string("ok kitchen-sink") }
			}
	}
	
	@Test
	@DisplayName("RequiredWhen · phoneBackup present when contactType=PHONE is accepted")
			/** RequiredWhen · phoneBackup present when contactType=PHONE is accepted			 */
	fun acceptsRequiredWhenSatisfied() {
		mockMvc.post("/api/all-constraints") {
			contentType = MediaType.APPLICATION_JSON
			content = json(
				AllConstraintsFixtures.valid(
					contactType = AllConstraintsRequest.ContactType.PHONE,
					phoneBackup = "14155550100",
				),
			)
		}
			.andExpect {
				status { isOk() }
			}
	}
	
	@Test
	@DisplayName("EmailOrPhone · email-only contact is accepted")
			/** EmailOrPhone · email-only contact is accepted			 */
	fun acceptsEmailOrPhoneEmailOnly() {
		mockMvc.post("/api/all-constraints") {
			contentType = MediaType.APPLICATION_JSON
			content = json(AllConstraintsFixtures.valid(contact = "only@example.com"))
		}
			.andExpect {
				status { isOk() }
			}
	}
	
	@Test
	@DisplayName("EmailOrPhone · phone-only contact is accepted")
			/** EmailOrPhone · phone-only contact is accepted			 */
	fun acceptsEmailOrPhonePhoneOnly() {
		mockMvc.post("/api/all-constraints") {
			contentType = MediaType.APPLICATION_JSON
			content = json(AllConstraintsFixtures.valid(contact = "14155552671"))
		}
			.andExpect {
				status { isOk() }
			}
	}
	
	@Test
	@DisplayName("OnCreate-only createOnlyNote is ignored under default HTTP groups (null accepted)")
			/** OnCreate-only createOnlyNote is ignored under default HTTP groups (null accepted)			 */
	fun acceptsNullCreateOnlyNoteUnderDefaultGroups() {
		mockMvc.post("/api/all-constraints") {
			contentType = MediaType.APPLICATION_JSON
			content = json(AllConstraintsFixtures.valid(createOnlyNote = null))
		}
			.andExpect {
				status { isOk() }
			}
	}
	
	@Test
	@DisplayName("password and card values are absent from constraint error JSON")
			/** password and card values are absent from constraint error JSON			 */
	fun secretsAreAbsentFromErrorJson() {
		val password = "securepass1!"
		val card = "4111111111111112"
		val body = mockMvc.post("/api/all-constraints") {
			contentType = MediaType.APPLICATION_JSON
			content = json(AllConstraintsFixtures.valid(password = password, card = card))
		}
			.andExpect {
				status { isBadRequest() }
			}
			.andReturn().response.contentAsString
		assertThat(body).doesNotContain(password)
		assertThat(body).doesNotContain(card)
	}
	
	@ParameterizedTest(name = "{0}")
	@MethodSource("violations")
	@DisplayName("rejects when a single constraint is violated")
			/** rejects when a single constraint is violated			 */
	fun rejectsSingleConstraintViolation(
		caseName: String,
		payload: AllConstraintsRequest,
		path: String,
		code: String,
	) {
		mockMvc.post("/api/all-constraints") {
			contentType = MediaType.APPLICATION_JSON
			content = json(payload)
		}
			.andExpect {
				status { isBadRequest() }
				jsonPath("$.errors[?(@.path == '$path')].code") { value(code) }
			}
	}
	
	/**
	 * @param payload kitchen-sink request
	 * @return JSON document for `POST /api/all-constraints`	 
	 */
	private fun json(payload: AllConstraintsRequest): String = objectMapper.writeValueAsString(payload)
	
	companion object {
		
		/**
		 * One `(caseName, payload, path, code)` row per kitchen-sink constraint failure.
		 *
		 * @return JUnit arguments consumed by [rejectsSingleConstraintViolation]
		 */
		@JvmStatic
		fun violations(): Stream<Arguments> = AllConstraintsFixtures.violations()
			.map { Arguments.of(it.name, it.payload, it.path, it.code) }
			.stream()
	}
}
