/*
 * Copyright 2026 Ghaylan Saada
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.ghaylan.validata.processor.codegen

import io.ghaylan.validata.processor.fqns.CodegenFqns
import io.ghaylan.validata.processor.model.GeneratedMetadataClassModel

/**
 * Renders a generated `*Constraint` metadata class from [GeneratedMetadataClassModel].
 *
 * Role markers (`@ConstraintMessage` / `@ConstraintGroups`) are declaration-time only and are
 * **not** copied onto generated properties — those become `override val message` / `groups`.
 */
internal object ConstraintMetadataCodeWriter {
	
	/**
	 * @param model validated metadata class model
	 * @return complete Kotlin file source
	 */
	fun write(model: GeneratedMetadataClassModel): String {
		val builder = KotlinSourceBuilder(model.packageName)
		builder.addImport(CodegenFqns.CONSTRAINT_METADATA)
		builder.addImport(model.annotationFqcn)

		val annotationSimpleName = model.annotationFqcn.substringAfterLast('.')

		for (property in model.properties) {
			for (ann in property.markerAnnotationsSource) {
				collectImportsFromAnnotationLine(ann).forEach(builder::addImport)
			}
			property.typeImports.forEach(builder::addImport)
		}

		builder.line("/**")
		builder.line(" * Generated metadata for [$annotationSimpleName].")
		builder.line(" *")
		builder.line(" * DO NOT EDIT — generated by validata-processor from the constraint annotation.")
		builder.line(" */")
		builder.line("data class ${model.simpleName}(")
		builder.indented {
			model.properties.forEachIndexed { index, prop ->
				for (ann in prop.markerAnnotationsSource) {
					line(ann)
				}
				val prefix = when {
					prop.isMessage || prop.isGroups -> "override val"
					else -> "val"
				}
				val comma = if (index == model.properties.lastIndex) "" else ","
				line("$prefix ${prop.name}: ${prop.typeSource}$comma")
			}
		}
		builder.line(") : ConstraintMetadata()")
		return builder.build(model.annotationFqcn)
	}
	
	private fun collectImportsFromAnnotationLine(line: String): List<String> {
		val imports = mutableListOf<String>()
		if (line.contains("ConstraintArg")) {
			imports += CodegenFqns.CONSTRAINT_ARG
			imports += CodegenFqns.CONSTRAINT_ARG_KIND
			if (line.contains("ConstraintArgTarget")) {
				imports += CodegenFqns.CONSTRAINT_ARG_TARGET
			}
		}
		if (line.contains("PropertyRef")) {
			imports += CodegenFqns.PROPERTY_REF
			if (line.contains("PropertyRefScope")) {
				imports += CodegenFqns.PROPERTY_REF_SCOPE
			}
			if (line.contains("PropertyRefCompatibilityKind")) {
				imports += CodegenFqns.PROPERTY_REF_COMPATIBILITY_KIND
			}
		}
		return imports
	}
}
