/*
 * Copyright 2026 Ghaylan Saada
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.ghaylan.validata.processor.codegen

import io.ghaylan.validata.schema.types.TypeNames

/**
 * Small, dependency-free Kotlin source assembler shared by every code writer in this processor.
 *
 * Centralizes indentation as blocks nest, deduplicated import tracking, and a uniform
 * generated-file header.
 *
 * @property packageName Kotlin package for the generated file (written as `package …`).*
 * 
 * @author Ghaylan Saada
 */
internal class KotlinSourceBuilder(
	private val packageName: String,
) {
	
	/**
	 * Deduplicated, sorted FQCNs to emit as `import` lines.
	 */
	private val imports = sortedSetOf<String>()
	
	/**
	 * Accumulated body lines (after package / imports).
	 */
	private val body = StringBuilder()
	
	/**
	 * Current indent depth in units of four spaces.
	 */
	private var indentLevel = 0
	
	/**
	 * `@file:…` annotations emitted before the package declaration, in insertion order.
	 */
	private val fileAnnotations = mutableListOf<String>()
	
	/**
	 * Records a `@file:…` annotation emitted before the package declaration.
	 *
	 * Side effects: appends to [fileAnnotations] when [annotation] is non-blank.
	 *
	 * @param annotation Full annotation text including `@file:` (e.g. `@file:Suppress(…)`).	 
	 */
	fun addFileAnnotation(annotation: String) {
		if (annotation.isNotBlank()) fileAnnotations += annotation
	}
	
	/**
	 * Records a fully qualified type to import.
	 *
	 * Types in [packageName], auto-imported `kotlin.*` / `java.lang.*`, blank, or already present
	 * are ignored so the emitted import block stays minimal and deterministic.
	 * `kotlin.reflect.*` is **not** auto-imported and is therefore allowed (e.g. `KClass`).
	 *
	 * Side effects: may add [fqcn] to [imports].
	 *
	 * @param fqcn Fully qualified class name (no `import` keyword).
	 */
	fun addImport(fqcn: String) {
		if (fqcn.isBlank()) return
		val isKotlinReflect = fqcn.startsWith(TypeNames.KOTLIN_REFLECT_PACKAGE_PREFIX)
		if (!isKotlinReflect &&
			(fqcn.startsWith(TypeNames.KOTLIN_PACKAGE_PREFIX) ||
				fqcn.startsWith(TypeNames.JAVA_LANG_PACKAGE_PREFIX))
		) {
			return
		}
		val lastDot = fqcn.lastIndexOf('.')
		if (lastDot <= 0) return
		val typePackage = fqcn.substring(0, lastDot)
		if (typePackage == packageName) return
		imports += fqcn
	}
	
	/**
	 * Appends one line at the current indentation, or a blank line when [text] is empty.
	 *
	 * Side effects: appends to [body].
	 *
	 * @param text Line content without leading whitespace; empty means blank line.	 
	 */
	fun line(text: String = "") {
		if (text.isEmpty()) {
			body.append('\n')
			return
		}
		body.append(indentFor(indentLevel))
		body.append(text).append('\n')
	}
	
	/**
	 * Appends [header] `{`, runs [content] one indent deeper, then closes with `}`.
	 *
	 * Side effects: appends to [body]; temporarily increments [indentLevel].
	 *
	 * @param header Block opener such as `fun entries(): List<…>` or `if (x)`.
	 * @param content Nested lines written at indent + 1.	 
	 */
	fun block(
		header: String,
		content: KotlinSourceBuilder.() -> Unit
	) {
		line("$header {")
		indentLevel++
		content()
		indentLevel--
		line("}")
	}
	
	/**
	 * Runs [content] one indent level deeper without wrapping braces.
	 *
	 * Used for multi-line argument lists inside a constructor call.
	 *
	 * Side effects: temporarily increments [indentLevel]; [content] appends to [body].
	 *
	 * @param content Nested lines.	 
	 */
	fun indented(content: KotlinSourceBuilder.() -> Unit) {
		indentLevel++
		content()
		indentLevel--
	}
	
	/**
	 * Assembles the final source text: header banner, package, sorted imports, then body.
	 *
	 * Side effects: none (does not mutate builder state).
	 *
	 * @param sourceComment Human-readable origin (annotated type / module), written into the
	 *    `// Source:` banner line.
	 * @return Complete Kotlin file contents.	 
	 */
	fun build(sourceComment: String): String {
		val out = StringBuilder()
		out.appendLine("// Generated by validata-processor. Do not edit by hand — re-run the build instead.")
		out.appendLine("// Source: $sourceComment")
		out.appendLine()
		for (ann in fileAnnotations) {
			out.appendLine(ann)
		}
		if (fileAnnotations.isNotEmpty()) out.appendLine()
		out.appendLine("package $packageName")
		out.appendLine()
		for (imp in imports) {
			out.appendLine("import $imp")
		}
		if (imports.isNotEmpty()) out.appendLine()
		out.append(body)
		return out.toString()
	}
	
	companion object {
		
		/**
		 * Precomputed `"    ".repeat(n)` for levels 0..16; deeper levels fall back to [String.repeat].
		 */
		private val INDENTS: Array<String> = Array(17) { level -> "    ".repeat(level) }
		
		/**
		 * Indentation prefix for [indentLevel].
		 *
		 * Side effects: none.
		 *
		 * @param level Indent depth (0 = no indent).
		 * @return Space prefix for one line at [level].		 
		 */
		private fun indentFor(level: Int): String =
			if (level < INDENTS.size) INDENTS[level] else "    ".repeat(level)
	}
}
