/*
 * Copyright 2026 Ghaylan Saada
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.ghaylan.validata.constraint.composition

import io.ghaylan.validata.constraint.ConstraintMetadata
import io.ghaylan.validata.model.ConstraintErrorCode
import io.ghaylan.validata.schema.constraint.CompiledConstraint
import kotlin.reflect.KClass

/**
 * Hand-written metadata for a composed OR (or future AND-wrapper) constraint site.
 *
 * Not generated by KSP and not registered in the constraint catalog. KSP emits constructor
 * literals that nest leaf [CompiledConstraint]s as [children].
 *
 * @property message Optional override when every active child fails. Blank uses
 *   [ConstraintErrorCode.CONSTRAINT_UNSATISFIABLE] default.
 * @property groups Outer groups that gate the whole composition.
 * @property children Leaf compiled constraints evaluated by [CompositionOrRunner].
 * 
 * @author Ghaylan Saada
 */
data class CompositionConstraint(
	override val message: String,
	override val groups: Set<KClass<*>>,
	val children: List<CompiledConstraint>,
): ConstraintMetadata()
