/*
 * Copyright 2026 Ghaylan Saada
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.ghaylan.validata.processor.codegen

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test

/**
 * Unit tests for [KotlinSourceBuilder] — indentation, imports, and deterministic headers.
 */
class KotlinSourceBuilderTest {

	@Test
	@DisplayName("build emits the fixed header banner, package, sorted imports, and body")
	fun emitsHeaderPackageImportsAndBody() {
		val builder = KotlinSourceBuilder("com.acme.generated")
		builder.addImport("com.acme.Foo")
		builder.addImport("com.acme.Bar")
		builder.addImport("com.acme.Foo") // duplicate ignored
		builder.addImport("kotlin.String") // skipped (auto-imported)
		builder.addImport("kotlin.reflect.KClass") // kept (not auto-imported)
		builder.addImport("com.acme.generated.Local") // same package skipped
		builder.line("/** Generated for tests. */")
		builder.block("object Sample") {
			line("val x = 1")
		}

		val once = builder.build("com.acme.Source")
		assertThat(once).startsWith(
			"// Generated by validata-processor. Do not edit by hand — re-run the build instead.\n" +
				"// Source: com.acme.Source\n",
		)
		assertThat(once).contains("package com.acme.generated\n")
		assertThat(once).contains("import com.acme.Bar\nimport com.acme.Foo\n")
		assertThat(once).contains("import kotlin.reflect.KClass\n")
		assertThat(once).contains("object Sample {\n    val x = 1\n}\n")
		assertThat(once).doesNotContain("import kotlin.String")
		assertThat(once).doesNotContain("import com.acme.generated.Local")
	}

	@Test
	@DisplayName("two builds with the same inputs produce identical source")
	fun deterministicOutput() {
		fun render(): String {
			val builder = KotlinSourceBuilder("com.acme.generated")
			builder.addImport("z.Zed")
			builder.addImport("a.Aye")
			builder.block("fun entries()") {
				line("return listOf(1, 2)")
			}
			return builder.build("fixture")
		}
		assertThat(render()).isEqualTo(render())
	}
}
